version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
    networks:
      - authnet

networks:
  authnet:
    driver: bridge

